import { writable } from 'svelte/store'
export const windowsScrollY = writable(0)
export const headerHeight = writable(0)
export const headerToggleHandler = writable(true)
export const ControlPanelToggleHandler = writable(false)
export const ToCToggleHandler = writable(false)
export const ArticleBox: any = writable(null)
export const ToCBox: any = writable(null)
export const specialHandler = writable(false)
// export const windowsWidth = writable(0)
